NasDB/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
    #path('', views.index, name = 'index'),
    #path('organisations/', views.NasOrganisationListView.as_view(), name = 'nas-organisations'),
    path('organisations/', views.nasorganisation_listview, name = 'nas-organisations'),
    path('organisation/<int:pk>', views.NasOrganisationDetailView.as_view(), name = 'nas-organisation-detail'),
    path('organisation/create/', views.NasOrganisationCreate.as_view(), name = 'nas-organisation_create'),
    path('organisation/<int:pk>/update', views.NasOrganisationUpdate.as_view(), name = 'nas-organisation_update'),
    path('organisation/<int:pk>/delete', views.NasOrganisationDelete.as_view(), name = 'nas-organisation_delete'),
    path('instructional-staff/', views.InstructionalStaffListView.as_view(), name= 'instructional-staff'),
    path('instructional-staff/<int:pk>', views.InstructionalStaffDetailView.as_view(), name= 'instructional_staff-detail'),
    path('instructional-staff/create/', views.InstructionalStaffCreate.as_view(), name = 'instructional-staff_create'),
    path('instructional-staff/<int:pk>/update', views.InstructionalStaffUpdate.as_view(), name= 'instructional-staff_update'),
    path('instructional-staff/<int:pk>/delete', views.InstructionalStaffDelete.as_view(), name= 'instructional-staff_delete'),
    path('apprentice-trainees/', views.ApprenticeTraineeListView.as_view(), name= 'apprentice-trainee'),
    path('apprentice-trainee/<int:pk>', views.ApprenticeTraineeDetailView.as_view(), name= 'apprentice_trainee-detail'),
    path('apprentice-trainee/create/', views.ApprenticeTraineeCreate.as_view(), name = 'apprentice-trainee_create'),
    path('apprentice-trainee/<int:pk>/update', views.ApprenticeTraineeUpdate.as_view(), name= 'apprentice-trainee_update'),
    path('apprentice-trainee/<int:pk>/delete', views.ApprenticeTraineeDelete.as_view(), name= 'apprentice-trainee_delete'),


    url(r'^search/$', views.nasfilter, name='nas-search'),
]

TTA/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views

urlpatterns = [
    #path('', views.index, name = 'index'),
    #path('trainees/', views.TraineeListView.as_view(), name = 'trainees'),
    path('trainees/', views.trainee_list_view, name = 'trainees'),
    path('centres/', views.centre_list_view, name = 'centres'),
    path('trainee/<int:pk>', views.TraineeDetailView.as_view(), name = 'trainee-detail'),
    path('centre/<int:pk>', views.CentreDetailView.as_view(), name = 'centre-detail'),
    url(r'^search/$', views.traineeFilter, name='trainee_search'),
    path('trainee/create', views.TraineeCreate.as_view(), name = 'trainee_create'),
    path('trainee/<int:pk>/update', views.TraineeUpdate.as_view(), name = 'trainee_update'),
    path('trainee/<int:pk>/delete', views.TraineeDelete.as_view(), name = 'trainee_delete'),
    path('centre/create', views.CentreCreate.as_view(), name = 'centre_create'),
    path('centre/<int:pk>/update', views.CentreUpdate.as_view(), name = 'centre_update'),
    path('centre/<int:pk>/delete', views.CentreDelete.as_view(), name = 'centre_delete'),
]

databank/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('main.urls')),
    path('client/', include('ClientDB.urls')),
    path('nas/', include ('NasDB.urls')),
    path('tta/', include('TTA.urls')),
    path('staff/', include('StaffDB.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NasDB/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey, ManyToManyField
from django.urls import reverse #Used to generate URLS by reversing the URL Patterns
from django.db.models.fields.files import ImageField
from PIL import Image
from django.utils.html import format_html
from django.utils.safestring import mark_safe
from datetime import datetime, date
from django.utils import timezone
from django.contrib.auth.models import User
import uuid


class Sector(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)

    class Meta:
        ordering = ('name', )
        verbose_name = 'Sector'
        verbose_name_plural = 'Sectors'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("nas-organisation_by_sector", args=[self.slug])

class State(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)

    class Meta:
        ordering = ('name', )
        verbose_name = 'State'
        verbose_name_plural = 'States'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("nas-organisation_by_state", args=[self.slug])

class Type(models.Model):
    name = models.CharField(max_length= 200)
    slug = models.SlugField(max_length = 200)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ('name', )
        verbose_name = 'type'
        verbose_name_plural = 'types'
    
    def get_absolute_url(self):
        return reverse("nas-organisation_by_trainingrecord", args=[self.slug])

class RecruitmentAndSelection(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ('name', )
        verbose_name = 'Recruitment and Selection Method'
        verbose_name_plural =  'Recruitment and Selection Methods'

    def get_absolute_url(self):
        return reverse("nas-organisation_by_recruitmentandselection", args=[self.slug])


class TrainingRecord(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length= 200)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ('name', )
        verbose_name = 'training record'
        verbose_name_plural = 'training records'
    
    def get_absolute_url(self):
        return reverse("nas-organisation_by_type", args=[self.slug])

class TradeArea(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length= 200)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ('name', )
        verbose_name = 'trade area'
        verbose_name_plural = 'trade areas'
    
    def get_absolute_url(self):
        return reverse("nas-organisation_by_tradearea", args=[self.slug])

class ProfessionalMembership(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length= 200)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ('name', )
        verbose_name = 'professional membership'
        verbose_name_plural = 'professional memberships'
    
    def get_absolute_url(self):
        return reverse("nas-organisation_by_type", args=[self.slug])


class NasOrganisation(models.Model):
    name =  models.CharField(max_length= 200)
    address = models.TextField(max_length= 200)
    contact_person = models.CharField(max_length=200, null=True)
    phone_number = models.IntegerField(null=True)
    email = models.EmailField(max_length=200, blank=True)
    state = models.ForeignKey('State', on_delete=models.SET_NULL, null=True)
    sector = models.ForeignKey('Sector', on_delete=models.SET_NULL, null=True)
    sub_Sector = models.CharField(max_length=200)
    trade_Area = ManyToManyField('TradeArea')
    type = models.ForeignKey('Type', on_delete=models.SET_NULL, null=True)
    YOE = models.DateField(auto_now= False)
    staff_Strength_Permanent = models.IntegerField(blank=True) 
    staff_Strength_Contract = models.IntegerField( blank=True)
    staff_Strength_Temporary = models.IntegerField( blank=True)
    id = models.AutoField(primary_key=True, help_text= "Unique Apprenticeship Number")
    CHOICE = [
        ('YES', 'YES'),
        ('NO', 'NO')
    ]
    
    cac_Registration = models.CharField(
        max_length=20,
        choices=CHOICE,
        blank=True,
        default='Yes'
    )

    cac_Reg_Number = models.IntegerField(blank=True, null=True)

    itf_Registration = models.CharField(
        max_length=20,
        choices=CHOICE,
        blank=True,
        default='No'
    )

    itf_Reg_Number = models.IntegerField(blank=True, null=True)


    APPRENTICE_SCHEME_STAGE = [
        ('Promotion', 'Promotion'),
        ('Appraisal', 'Appraisal'),
        ('Harmonisation', 'Harmonisation'),
        ('Installation', 'Installation'),
        ('Inspection, Supervision, Monitoring', 'Inspection, Supervision, Monitoring'),
    ]

    stage =  models.CharField(
        max_length=50, 
        choices= APPRENTICE_SCHEME_STAGE,
        blank=True,
        default = 'Promotion',
        help_text = 'Apprencticeship Stage',
    )

    #Promotion
    promotion_Officer =  models.CharField(max_length=200, blank=True)
    PROMOTION_REPORT_STATUS = [
        ('YES', 'YES'),
        ('NO', 'NO'),
       ]
    promotional_report_available = models.CharField(
        max_length=5,
        choices=PROMOTION_REPORT_STATUS,
        blank=True,
        default='NO',
        help_text='YES or NO'
    )
    promotional_report = models.FileField(upload_to= 'upload/nas/reports/promotion', blank=True)
    products =  models.CharField(max_length=200, blank=True)
    services = models.CharField(max_length=200, blank=True)
    tna = models.TextField(blank=True)

    #Apraisal
    appraisal_Officer =  models.CharField(max_length=200, blank=True)
    APPRAISAL_REPORT_STATUS = [
        ('YES', 'YES'),
        ('NO', 'NO'),
    ]
    curriculum_available = models.CharField(
        max_length=5,
        choices=APPRAISAL_REPORT_STATUS,
        blank=True,
        default='NO',
        help_text='YES or NO'
    )
    CURRICULUM = [
        ('ITF', 'ITF'),
        ('ORGANISATION DESIGN', 'ORGANISATION DESIGN'),
        ('NSQ', 'NSQ'),
        ('OTHERS', 'OTHERS'),
    ]
    curriculum_type = models.CharField(
        max_length=200,
        choices=CURRICULUM,
        blank=True,
        default='ITF',  
    )
    other_curriculum_type = models.CharField(max_length=200, blank=True)

    recruitment_and_Selection = ForeignKey(RecruitmentAndSelection, on_delete=models.SET_NULL, null=True, blank=True)
    
    training_Approach_Practical  = models.IntegerField(blank=True, null=True)
    training_Approach_Theory = models.IntegerField(blank=True, null=True)
    training_Approach_Otj = models.IntegerField(blank=True, null=True)
    
    TRAINING_REPORT_STATUS = [
        ('YES', 'YES'),
        ('NO', 'NO'),
    ]
    training_record_available = models.CharField(
        max_length=200,
        choices=TRAINING_REPORT_STATUS,
        blank=True,
        default='NO',
        
    )
    training_record_type = models.ManyToManyField(TrainingRecord, blank=True)

    CERTIFICATION_AVAILABLE_STATUS = [
        ('YES', 'YES'),
        ('NO', 'NO'),
    ]
    certification_available = models.CharField(
        max_length=5,
        choices=CERTIFICATION_AVAILABLE_STATUS,
        blank=True,
        default='NO',
        
    )
    CERTIFICATION = [
        ('CERTIFICATE OF PARTICIPATION', 'CERTIFICATE OF PARTICIPATION'),
        ('CERTIFICATE OF COMPETENCY', 'CERTIFICATE OF COMPETENCY'),
        ('CITY AND GUILD','CITY AND GUILD'),
        ('NABTEB', 'NABTEB'),
        ('NSQ', 'NSQ'),
        ('NUC/ATC', 'NUC/ATC'),
    ]

    certification_type = models.CharField(
        max_length=200,
        choices=CERTIFICATION,
        blank=True,
        default='CERTIFICATE OF PARTICIPATION',
        
    )

    APPRENTICESHIP_CONTRACT_AGREEMENT_STATUS = [
        ('YES', 'YES'),
        ('NO', 'NO'),
        
    ]

    apprenticeship_Contract_Agreement = models.CharField(
        max_length=5,
        choices=APPRENTICESHIP_CONTRACT_AGREEMENT_STATUS,
        blank=True,
        default='NO', 
    )

    welfare_for_Trainees = models.CharField(max_length=200, blank=True)

    appraisal_findings = models.TextField(blank=True, null=True)
    appraisal_recommendations = models.TextField(blank=True, null=True)
    appraisal_conclusion = models.TextField(blank=True, null=True)


    APPRAISAL_REPORT_STATUS = [
        ('YES', 'YES'),
        ('NO', 'NO'),
        
    ]
    appraisal_report_available = models.CharField(
        max_length=5,
        choices=APPRAISAL_REPORT_STATUS,
        blank=True,
        default='NO',
        
    )

    appraisal_report = models.FileField(upload_to= 'upload/nas/reports/appraisal', blank=True)

    #Harmonisation
    harmonisation_Officer =  models.CharField(max_length=200, null=True, blank=True)

    types_of_Apprenticeship_Installed = models.TextField(blank=True)
    apprencticeship_Type_Existing = models.TextField(blank=True)
    apprenticeship_Components_Lacking =  models.TextField(blank=True)
    apprenticeship_Components_Harmonised = models.TextField(blank=True)
    
    HARMONISATION_REPORT_STATUS = [
        ('YES', 'YES'),
        ('NO', 'NO'),
        
    ]
    harmonisation_report_available = models.CharField(
        max_length=5,
        choices=HARMONISATION_REPORT_STATUS,
        blank=True,
        default='NO',
       
    )
    harmonisation_report = models.FileField(upload_to= 'upload/nas/reports/harmonisation', blank=True)

    #Installation
    installation_Officer =  models.CharField(max_length=200, null=True, blank=True)

    apprenticeship_Type_Installed = models.TextField(blank=True)

NasDB/forms.py
from django.db.models import fields
from django import forms
from django.forms import ModelForm, widgets 

from .models import NasOrganisation, InstructionalStaff

class DateInput(forms.DateInput):
    input_type = 'date'

class NasOrganisationForm(ModelForm):
    class Meta:
        model =  NasOrganisation
        fields = '__all__'
        widgets = {
            'YOE': DateInput(),
            'DOPA':DateInput(),
            'DOFA': DateInput(),
        }

class InstructionalStaffForm(ModelForm):
    class Meta:
        model = InstructionalStaff
        fields = '__all__'
        widgets = {
            'doe': DateInput()
        }

NasDB/templates/NasDB/apprencticetrainee_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
 <h1>Delete ApprenticeTrainee</h1>

<p>Are you sure you want to delete the Apprentice Trainee: {{ apprencticetrainee}}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input class="btn btn-outline-secondary" type="submit" value="Yes, delete.">
</form>
</div>


{% endblock %}

NasDB/templates/NasDB/apprencticetrainee_form.html
{% extends "base.html" %}

{% include "django/forms/widgets/input.html" %}

{% load crispy_forms_tags %}

{% block content %}

  <div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Add Trainee</h1>
    <p class="lead">Use the form below to add an Apprentice Trainee to the Fund's NAS databank.</p>
  </div>
  </div>


  <div class="container-fluid">
    <form method="post" action="" enctype="multipart/form-data" >
      {% csrf_token %}
      
      <!-- General Information -->
      <h3 class="text-center" > Staff Information </h3>
       <hr class="sidebar-divider">

      <div class="form-row">
        <div class="form-group col-md-3 mb-0">
          {{ form.name|as_crispy_field }}
        </div>
        <div class="form-group col-md-3 mb-0">
          {{ form.trade_Area|as_crispy_field }}
        </div>
        <div class="form-group col-md-3 mb-0" >
          {{ form.doe|as_crispy_field }}
        </div>
        <div class="form-group col-md-3 mb-0" >
          {{ form.organisation|as_crispy_field }}
        </div>
      </div>

    


      <button value="Submit" type="submit" class="btn btn-primary">Save</button>
    </form>
  </div>

{% endblock %}

NasDB/templates/NasDB/instructionstaff_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
 <h1>Delete Instructional Staff</h1>

<p>Are you sure you want to delete the Staff: {{ instructionalstaff }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input class="btn btn-outline-secondary" type="submit" value="Yes, delete.">
</form>
</div>


{% endblock %}

NasDB/templates/NasDB/nasorganisation_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="jumbotron jumbotron-fluid">
    <div class="container-fluid">
        <div class="row">
            
            <div class="col-md-12">
                <h1 class="display-3 text-center">{{nasorganisation.name}} Detail Page</h1>              
            </div>
        </div>  
    </div>
</div> 



  <div class="container-fluid" >
    <div class="row">        
        <div class="card-columns " style="column-count: 1;">
            
            
            <!--General Information-->
            <div class="card mb-6">
                <div class="card-header">
                  <h3>General Information</h3>
                </div>
                <div class="card-body">
                    <p class="DTS"><strong>ADDRESS: </strong> {{nasorganisation.address}} </p>
                    <p class="DTS"><strong>CONTACT PERSON: </strong> {{nasorganisation.contact_person}} </p>
                    <p class="DTS"><strong>PHONE NUMBER: </strong> 0{{nasorganisation.phone_number}} </p>
                    <p class="DTS"><strong>EMAIL: </strong>{{nasorganisation.email}} </p>
                    <p class="DTS"><strong>STATE: </strong>{{nasorganisation.state}} </p>
                    <p class="DTS"><strong>ONWERSHIP TYPE: </strong>{{nasorganisation.type}} </p>
                    <p class="DTS"><strong>SECTOR: </strong>{{nasorganisation.sector}} </p>
                    <p class="DTS"><strong>SUB-SECTOR: </strong>{{nasorganisation.sub_Sector}} </p>
                    <p class="DTS"><strong>TRADE AREA: </strong>{{nasorganisation.trade_Area.all | join:', '}} </p>
                    {% comment %} <p> {% for trade_Area in nasorganisation.trade_Area.all %}{{trade_Area}} {%if not forloop.last%}, {%endif%}{%endfor%} </p> {% endcomment %}
                    <p class="DTS"><strong>STAFF STRENGTH (Permanent): </strong> {{nasorganisation.staff_Strength_Permanent}} </p>
                    <p class="DTS"><strong>STAFF STRENGTH (Contract): </strong> {{nasorganisation.staff_Strength_Contract}} </p>
                    <p class="DTS"><strong>STAFF STRENGTH (Temporary): </strong> {{nasorganisation.staff_Strength_Temporary}} </p>
                    <p class="DTS"><strong>DATE FORMED: </strong> {{nasorganisation.YOE}} </p>
                    <p class="DTS"><strong>REGISTERED WITH CAC: </strong> {{nasorganisation.cac_registration}} </p>
                    <p class="DTS"><strong>IF YES, CAC REG NUMBER: </strong> {{nasorganisation.cac_Reg_Number}} </p>
                    <p class="DTS"><strong>REGISTERED WITH ITF: </strong> {{nasorganisation.itf_registration}} </p>
                    <p class="DTS"><strong>IF YES, ITF REG NUMBER: </strong> {{nasorganisation.itf_Reg_Number}} </p>
                    <p class="DTS"><strong>STAGE: </strong>{{nasorganisation.stage}} </p>
                </div>
              </div>
        <!--Promotional Activities-->
        
            <div class="card mb-6">
                <div class="card-header">
                  <h3>Promotional Activities</h3>
                </div>
                <div class="card-body">
                    <p class="DTS"><strong>PROMOTIONAL OFFICER: </strong> {{nasorganisation.promotion_Officer}} </p>
                    <p class="DTS"><strong>PROMOTIONAL REPORT AVAILABLE: </strong> {{nasorganisation.promotional_report_available}} </p>
                    {% if nasorganisation.promotional_report %}
                    <p class="DTS"><strong>PROMOTIONAL REPORT: </strong> <a target="_blank" href="{{nasorganisation.promotional_report.url}}"> Download Report </a></p>
                    {% endif %}
                    <p class="DTS"><strong>PRODUCTS: </strong> {{nasorganisation.products}}</p>
                    <p class="DTS"><strong>SERVICES: </strong> {{nasorganisation.services}}</p>
                    <p class="DTS"><strong>TRAINING NEEDS ANALYSIS: </strong> {{nasorganisation.tna}} </p>
                </div>
              </div>

        <!--Appraisal Activities-->
        
            <div class="card mb-6">
                <div class="card-header">
                  <h3>Appraisal Activities</h3>
                </div>
                <div class="card-body">
                    <p class="DTS"><strong>APPRAISAL OFFICER: </strong> {{nasorganisation.appraisal_Officer}} </p>
                    <p class="DTS"><strong>CURRICULUM AVAILABLE: </strong> {{nasorganisation.curriculum_available}} </p>
                    <p class="DTS"><strong>CURRICULUM TYPE: </strong> {{nasorganisation.curriculum_type}} </p>
                    <p class="DTS"><strong>OTHER CURRICULUM TYPE: </strong> {{nasorganisation.other_curriculum_type}} </p>
                    <p class="DTS"><strong>RECRUITMENT AND SELECTION METHOD: </strong> {{nasorganisation.recruitment_and_Selection}} </p>
                    <p class="DTS"><strong>TRAINING RECORD AVAILABLE: </strong> {{nasorganisation.training_record_available}} </p>
                    <p class="DTS"><strong>TRAINING RECORD TYPE: </strong>{{nasorganisation.record_type}} </p>
                    
                    <p class="DTS"><strong>TRAINING APPROACH (PRACTICAL): </strong>{{nasorganisation.training_Approach_Practical}} % </p>
                    <p class="DTS"><strong>TRAINING APPROACH (THEORY): </strong>{{nasorganisation.training_Approach_Theory}} %</p>
                    <p class="DTS"><strong>TRAINING APPROACH (ON THE JOB): </strong>{{nasorganisation.training_Approach_}} %</p>

                    <p class="DTS"><strong>CERTIFICATION AVAILABLE: </strong>{{nasorganisation.certification_available}} </p>
                    <p class="DTS"><strong>CERTIFICATION TYPE: </strong>{{nasorganisation.certification_type}} </p>
                    <p class="DTS"><strong>APPRENTICESHIP CONTRACT AGREEMENT: </strong>{{nasorganisation.apprenticeship_Contract_Agreement}} </p>                   
                    <p class="DTS"><strong>APPRAISAL FINDINGS: </strong>{{nasorganisation.appraisal_findings}} </p>
                    <p class="DTS"><strong>APPRAISAL RECOMMENDATIONS: </strong>{{nasorganisation.appraisal_recommendations}} </p>
                    <p class="DTS"><strong>APPRAISAL CONCLUSION: </strong>{{nasorganisation.appraisal_conclusion}} </p>
                    
                    <p class="DTS"><strong>TRAINEE WELFARE: </strong>{{nasorganisation.welfare_for_Trainee}} </p>
                    <p class="DTS"><strong>APPRAISAL REPORT AVAILABLE: </strong> {{nasorganisation.appraisal_report_available}} </p>

                    {% if nasorganisation.appraisal_report %}
                    <p class="DTS"><strong>APPRAISAL REPORT: </strong> <a target="_blank" href = "{{nasorganisation.appraisal_report.url}}">Download Report</a></p>
                    {% endif %}
                    

                    
                </div>
              </div>

              <!--Harmonisation Activities-->
        
            <div class="card mb-6">
                <div class="card-header">
                  <h3>Harmonisation Activities</h3>
                </div>
                <div class="card-body">
                    <p class="DTS"><strong>HARMONISATION OFFICER: </strong> {{nasorganisation.harmonisation_Officer}} </p>
                    <p class="DTS"><strong>HARMONISATION REPORT AVAILABLE: </strong> {{nasorganisation.harmonisation_report_available}} </p>
                    {% if nasorganisation.harmonisation_report %}
                    <p class="DTS"><strong>HARMONISATION REPORT: </strong> <a target="_blank" href = "{{nasorganisation.harmonisation_report.url}}"> Download Report</a></p>
                    {% endif %}
                    
                </div>
              </div>
            
            <!--Installation Activities-->
        
            <div class="card mb-6">
                <div class="card-header">
                  <h3>Installation Activities</h3>
                </div>
                <div class="card-body">                   
                    <p class="DTS"><strong>INSTALLATION OFFICER: </strong> {{nasorganisation.installation_officer}} </p>
                    <p class="DTS"><strong>INSTALLATION REPORT AVAILABLE: </strong> {{nasorganisation.installation_report_available}} </p>
                    {% if nasorganisation.installation_report %}
                    <p class="DTS"><strong>INSTALLATION REPORT: </strong> <a target="_blank" href= "{{nasorganisation.installation_report}}">Download Report</a></p>
                    {% endif %}
                    
                </div>
              </div>
            
            <!--Inspection/Supervision/Monitoring Activities-->
        
            <div class="card mb-6">
                <div class="card-header">
                  <h3>Inspection/Supervision/Monitoring (ISM) Activities</h3>
                </div>
                <div class="card-body">
                    
                    
                    <p class="DTS"><strong>ISM OFFICER: </strong> {{nasorganisation.ISM_officer}} </p>
                    <p class="DTS"><strong>ISM REPORT AVAILABLE: </strong> {{nasorganisation.ISM_report_available}} </p>
                    {% if nasorganisation.ISM_report %}
                    <p class="DTS"><strong>ISM REPORT: </strong> <a href = "{{nasorganisation.ISM_report.url}}" target="_blank">Download Report</a> </p>
                    {% endif %}
                    
                    <p class="DTS"><strong>PLANNING OF TRAINING PROGRAMME: </strong> {{nasorganisation.planning_of_Training_Programme}} </p>
                    <p class="DTS"><strong>USE OF APPROPRIATE METHOD OF TRAINING: </strong> {{nasorganisation.use_of_Appropriate_Method_of_Training}} </p>
                    <p class="DTS"><strong>RECORD OF TRAINING PERFORMANCE: </strong> {{nasorganisation.record_of_Trainees_Performance}} </p>
                    <p class="DTS"><strong>ENTRIES IN TRAINEES LOGBOOK: </strong> {{nasorganisation.entries_in_Trainees_Logbook}}</p>
                    <p class="DTS"><strong>PROGRESS REPORT OF THE SCHEME: </strong> {{nasorganisation.planning_of_Training_Programme}} </p>
                    <p class="DTS"><strong>GENERAL RECORD KEEPING: </strong> {{nasorganisation.general_Record_Keeping}} </p>
                    

                    
                </div>
              </div>

              <!--Approvals and Certification-->
        
            <div class="card mb-6">
                <div class="card-header">
                  <h3>Approvals and Certification</h3>
                </div>
                <div class="card-body">                   
                    <p class="DTS"><strong>PROVISIONAL APPROVAL: </strong> {{nasorganisation.provisional_approval}} </p>
                    <p class="DTS"><strong>DATE OF PROVISIONAL APPROVAL: </strong> {{nasorganisation.DOPA}} </p>
                    <p class="DTS"><strong>FULL APPROVAL: </strong> {{nasorganisation.full_approval}} </p>
                    <p class="DTS"><strong>DATE OF FULL APPROVAL: </strong> {{nasorganisation.DOFA}} </p>
                    <p class="DTS"><strong>INSTALLATION REPORT: </strong> {{nasorganisation.installation_report}} </p>
                </div>
              </div>


        </div> <!--End of Card Column-->
    </div> <!--End of Row-->
  </div>















 
        {% if perms.NasDB.change_nasorganisation %}
      
      <div class="container">
      <a class='btn btn-outline-secondary' href="{% url 'nas-organisation_update' nasorganisation.id %}">Update {{ nasorganisation }}'s Record</a>
      
      <a class='btn btn-outline-secondary' href="{% url 'nas-organisation_delete' nasorganisation.id %}">Delete {{ nasorganisation }}'s Record</a>
      
      </div>
      
        {% endif %}
    






{% endblock content %}